version: '3.8'

services:
  database:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=google_scraper_test
    ports:
      - '5432:5432'
  redis:
    image: redis
    ports:
      - "6380:6379"
