name: Deploy

on: push

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - name: Set BRANCH_TAG
        uses: nimblehq/branch-tag-action@v1.2
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - name: Set HEROKU_APP_NAME
        run: |
          if [[ $BRANCH_TAG = "latest" ]]
          then
            echo "HEROKU_APP_NAME=${{ secrets.HEROKU_APP_NAME }}" >> $GITHUB_ENV
          else
            echo "HEROKU_APP_NAME=${{ secrets.HEROKU_APP_NAME }}-staging" >> $GITHUB_ENV
          fi

      - name: Set staging database url
        if: ${{ env.BRANCH_TAG != 'latest' }}
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_STAGING }}
        run: |
          echo "DATABASE_URL=$DATABASE_URL" >> $GITHUB_ENV

      - name: Set production database url
        if: ${{ env.BRANCH_TAG == 'latest' }}
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_PRODUCTION }}
        run: |
          echo "DATABASE_URL=$DATABASE_URL" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker-compose pull || true
          docker-compose build --build-arg DATABASE_URL=$DATABASE_URL
          docker-compose push app

      - name: Log in to Heroku container
        run: heroku container:login

      - name: Publish application
        run: |
          heroku container:push --arg DATABASE_URL=$DATABASE_URL --recursive -a $HEROKU_APP_NAME
          heroku container:release web worker -a $HEROKU_APP_NAME
